// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2FEY5oUj6pxZvvxC3afa2FV4FmjLaSzk',
    appId: '1:987705557812:web:2e00ad29a57f9dd6d0db61',
    messagingSenderId: '987705557812',
    projectId: 'cattle-pulse',
    authDomain: 'cattle-pulse.firebaseapp.com',
    storageBucket: 'cattle-pulse.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_ke4B87hnoBMt9ze2P4Q82i1onX3eZzo',
    appId: '1:987705557812:android:6e1985d303d394b3d0db61',
    messagingSenderId: '987705557812',
    projectId: 'cattle-pulse',
    storageBucket: 'cattle-pulse.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfZBkyARpOKN7nWTkVVJ4zx7HDxmiigAY',
    appId: '1:987705557812:ios:52191385cdad2599d0db61',
    messagingSenderId: '987705557812',
    projectId: 'cattle-pulse',
    storageBucket: 'cattle-pulse.firebasestorage.app',
    iosBundleId: 'com.example.cattlePulse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfZBkyARpOKN7nWTkVVJ4zx7HDxmiigAY',
    appId: '1:987705557812:ios:52191385cdad2599d0db61',
    messagingSenderId: '987705557812',
    projectId: 'cattle-pulse',
    storageBucket: 'cattle-pulse.firebasestorage.app',
    iosBundleId: 'com.example.cattlePulse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2FEY5oUj6pxZvvxC3afa2FV4FmjLaSzk',
    appId: '1:987705557812:web:4cf95ca0adeaf474d0db61',
    messagingSenderId: '987705557812',
    projectId: 'cattle-pulse',
    authDomain: 'cattle-pulse.firebaseapp.com',
    storageBucket: 'cattle-pulse.firebasestorage.app',
  );
}
