// screens/add_cattle_screen.dart
import 'package:flutter/material.dart';
import 'package:cattle_pulse/screens/side_menu_screens/home_screen/cattle_management_screen/cattle_model.dart';
import 'package:cattle_pulse/screens/side_menu_screens/home_screen/cattle_management_screen/cattle_service.dart';

class AddCattleScreen extends StatefulWidget {
  const AddCattleScreen({super.key});

  @override
  State<AddCattleScreen> createState() => _AddCattleScreenState();
}

class _AddCattleScreenState extends State<AddCattleScreen> {
  final _formKey = GlobalKey<FormState>();
  final CattleService _cattleService = CattleService();

  final TextEditingController _nameController = TextEditingController();
  final TextEditingController _tagIdController = TextEditingController();
  final TextEditingController _breedController = TextEditingController();
  final TextEditingController _ageController = TextEditingController();
  final TextEditingController _weightController = TextEditingController();

  // Feeding profile controllers
  final TextEditingController _totalFeedController =
      TextEditingController(text: "8");
  final TextEditingController _hayController =
      TextEditingController(text: "30");
  final TextEditingController _binolaController =
      TextEditingController(text: "20");
  final TextEditingController _chokarController =
      TextEditingController(text: "20");
  final TextEditingController _makaiController =
      TextEditingController(text: "15");
  final TextEditingController _waterController =
      TextEditingController(text: "15");

  String _selectedHealthStatus = "Healthy";
  String _selectedFeedType = "Dry Feed"; // Fixed: Now matches dropdown values
  bool _isLoading = false;

  @override
  void dispose() {
    _nameController.dispose();
    _tagIdController.dispose();
    _breedController.dispose();
    _ageController.dispose();
    _weightController.dispose();
    _totalFeedController.dispose();
    _hayController.dispose();
    _binolaController.dispose();
    _chokarController.dispose();
    _makaiController.dispose();
    _waterController.dispose();
    super.dispose();
  }

  Future<void> _saveCattle() async {
    if (!_formKey.currentState!.validate()) {
      return;
    }

    // Validate percentages add up to 100
    final int totalPercent = int.parse(_hayController.text) +
        int.parse(_binolaController.text) +
        int.parse(_chokarController.text) +
        int.parse(_makaiController.text) +
        int.parse(_waterController.text);

    if (totalPercent != 100) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Row(
            children: [
              const Icon(Icons.warning, color: Colors.white),
              const SizedBox(width: 8),
              Text(
                  "Feed percentages must add up to 100% (currently $totalPercent%)"),
            ],
          ),
          backgroundColor: Colors.orange,
          behavior: SnackBarBehavior.floating,
          shape:
              RoundedRectangleBorder(borderRadius: BorderRadius.circular(10)),
        ),
      );
      return;
    }

    setState(() {
      _isLoading = true;
    });

    try {
      final feederProfile = AutoFeederProfile(
        feedType: _selectedFeedType,
        totalFeedKg: int.parse(_totalFeedController.text),
        hayPercent: int.parse(_hayController.text),
        binolaPercent: int.parse(_binolaController.text),
        chokarPercent: int.parse(_chokarController.text),
        makaiLeavesPercent: int.parse(_makaiController.text),
        waterPercent: int.parse(_waterController.text),
      );

      final cattle = CattleModel(
        id: '', // Will be generated by Firebase
        name: _nameController.text.trim(),
        tagId: _tagIdController.text.trim().toUpperCase(),
        breed: _breedController.text.trim(),
        ageMonths: int.parse(_ageController.text),
        weightKg: int.parse(_weightController.text),
        healthStatus: _selectedHealthStatus,
        feederProfile: feederProfile,
      );

      final id = await _cattleService.addCattle(cattle);

      setState(() {
        _isLoading = false;
      });

      if (id != null) {
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              content: const Row(
                children: [
                  Icon(Icons.check_circle, color: Colors.white),
                  SizedBox(width: 8),
                  Text("Cattle added successfully!"),
                ],
              ),
              backgroundColor: const Color(0xFF4CAF50),
              behavior: SnackBarBehavior.floating,
              shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(10)),
            ),
          );
          Navigator.pop(context, true); // Return true to indicate success
        }
      } else {
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              content: const Row(
                children: [
                  Icon(Icons.error, color: Colors.white),
                  SizedBox(width: 8),
                  Text("Failed to add cattle. Please try again."),
                ],
              ),
              backgroundColor: Colors.red,
              behavior: SnackBarBehavior.floating,
              shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(10)),
            ),
          );
        }
      }
    } catch (e) {
      setState(() {
        _isLoading = false;
      });

      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Row(
              children: [
                const Icon(Icons.error, color: Colors.white),
                const SizedBox(width: 8),
                Text("Error: ${e.toString()}"),
              ],
            ),
            backgroundColor: Colors.red,
            behavior: SnackBarBehavior.floating,
            shape:
                RoundedRectangleBorder(borderRadius: BorderRadius.circular(10)),
          ),
        );
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final colorScheme = Theme.of(context).colorScheme;

    return Scaffold(
      appBar: AppBar(
        title: const Text("Add New Cattle"),
        centerTitle: true,
        elevation: 0,
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16),
        child: Form(
          key: _formKey,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Center(
                child: Container(
                  padding: const EdgeInsets.all(24),
                  decoration: BoxDecoration(
                    color: colorScheme.primary.withOpacity(0.1),
                    shape: BoxShape.circle,
                  ),
                  child: Icon(Icons.pets, size: 64, color: colorScheme.primary),
                ),
              ),
              const SizedBox(height: 32),

              // Basic Information Section
              Text(
                "Basic Information",
                style: TextStyle(
                  fontSize: 18,
                  fontWeight: FontWeight.bold,
                  color: Colors.grey[800],
                ),
              ),
              const SizedBox(height: 16),

              _FormField(
                controller: _nameController,
                icon: Icons.label,
                label: "Cattle Name",
                hint: "Enter cattle name",
              ),
              const SizedBox(height: 16),
              _FormField(
                controller: _tagIdController,
                icon: Icons.qr_code_2,
                label: "Tag ID",
                hint: "Enter tag ID (e.g., C-102)",
              ),
              const SizedBox(height: 16),
              _FormField(
                controller: _breedController,
                icon: Icons.category,
                label: "Breed",
                hint: "Enter breed (e.g., Sahiwal)",
              ),
              const SizedBox(height: 16),
              _FormField(
                controller: _ageController,
                icon: Icons.cake,
                label: "Age (months)",
                hint: "Enter age in months",
                keyboardType: TextInputType.number,
              ),
              const SizedBox(height: 16),
              _FormField(
                controller: _weightController,
                icon: Icons.monitor_weight,
                label: "Weight (kg)",
                hint: "Enter weight in kg",
                keyboardType: TextInputType.number,
              ),
              const SizedBox(height: 16),

              Text(
                "Health Status",
                style: TextStyle(
                  fontSize: 14,
                  fontWeight: FontWeight.w600,
                  color: Colors.grey[700],
                ),
              ),
              const SizedBox(height: 8),
              Row(
                children: [
                  Expanded(
                    child: _HealthStatusChip(
                      label: "Healthy",
                      icon: Icons.check_circle,
                      color: const Color(0xFF4CAF50),
                      isSelected: _selectedHealthStatus == "Healthy",
                      onTap: () =>
                          setState(() => _selectedHealthStatus = "Healthy"),
                    ),
                  ),
                  const SizedBox(width: 8),
                  Expanded(
                    child: _HealthStatusChip(
                      label: "Sick",
                      icon: Icons.warning,
                      color: const Color(0xFFF44336),
                      isSelected: _selectedHealthStatus == "Sick",
                      onTap: () =>
                          setState(() => _selectedHealthStatus = "Sick"),
                    ),
                  ),
                  const SizedBox(width: 8),
                  Expanded(
                    child: _HealthStatusChip(
                      label: "Treatment",
                      icon: Icons.medical_services,
                      color: const Color(0xFFFF9800),
                      isSelected: _selectedHealthStatus == "Under Treatment",
                      onTap: () => setState(
                          () => _selectedHealthStatus = "Under Treatment"),
                    ),
                  ),
                ],
              ),
              const SizedBox(height: 32),

              // Feeding Profile Section
              Text(
                "Feeding Profile",
                style: TextStyle(
                  fontSize: 18,
                  fontWeight: FontWeight.bold,
                  color: Colors.grey[800],
                ),
              ),
              const SizedBox(height: 16),

              Text(
                "Feed Type",
                style: TextStyle(
                  fontSize: 14,
                  fontWeight: FontWeight.w600,
                  color: Colors.grey[700],
                ),
              ),
              const SizedBox(height: 8),

              DropdownButtonFormField<String>(
                initialValue: _selectedFeedType,
                decoration: InputDecoration(
                  prefixIcon: const Icon(Icons.restaurant),
                  filled: true,
                  border: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(12),
                  ),
                ),
                items: const [
                  DropdownMenuItem(value: "Dry Feed", child: Text("Dry Feed")),
                  DropdownMenuItem(value: "Wet Feed", child: Text("Wet Feed")),
                  DropdownMenuItem(
                      value: "Mixed Feed", child: Text("Mixed Feed")),
                ],
                onChanged: (value) {
                  setState(() {
                    _selectedFeedType = value!;
                  });
                },
              ),
              const SizedBox(height: 16),

              _FormField(
                controller: _totalFeedController,
                icon: Icons.scale,
                label: "Total Feed (Kg)",
                hint: "Enter total feed in kg",
                keyboardType: TextInputType.number,
              ),
              const SizedBox(height: 16),

              Text(
                "Feed Composition (% - Must total 100%)",
                style: TextStyle(
                  fontSize: 14,
                  fontWeight: FontWeight.w600,
                  color: Colors.grey[700],
                ),
              ),
              const SizedBox(height: 8),
              Row(
                children: [
                  Expanded(
                    child: _FormField(
                      controller: _hayController,
                      icon: Icons.grass,
                      label: "Hay",
                      hint: "%",
                      keyboardType: TextInputType.number,
                    ),
                  ),
                  const SizedBox(width: 8),
                  Expanded(
                    child: _FormField(
                      controller: _binolaController,
                      icon: Icons.grain,
                      label: "Binola",
                      hint: "%",
                      keyboardType: TextInputType.number,
                    ),
                  ),
                ],
              ),
              const SizedBox(height: 12),
              Row(
                children: [
                  Expanded(
                    child: _FormField(
                      controller: _chokarController,
                      icon: Icons.breakfast_dining,
                      label: "Chokar",
                      hint: "%",
                      keyboardType: TextInputType.number,
                    ),
                  ),
                  const SizedBox(width: 8),
                  Expanded(
                    child: _FormField(
                      controller: _makaiController,
                      icon: Icons.eco,
                      label: "Makai",
                      hint: "%",
                      keyboardType: TextInputType.number,
                    ),
                  ),
                ],
              ),
              const SizedBox(height: 12),
              _FormField(
                controller: _waterController,
                icon: Icons.water_drop,
                label: "Water",
                hint: "Enter percentage",
                keyboardType: TextInputType.number,
              ),
              const SizedBox(height: 32),

              ElevatedButton.icon(
                onPressed: _isLoading ? null : _saveCattle,
                icon: _isLoading
                    ? const SizedBox(
                        width: 20,
                        height: 20,
                        child: CircularProgressIndicator(
                          strokeWidth: 2,
                          valueColor:
                              AlwaysStoppedAnimation<Color>(Colors.white),
                        ),
                      )
                    : const Icon(Icons.check),
                label: Text(_isLoading ? "Saving..." : "Save Cattle"),
                style: ElevatedButton.styleFrom(
                  minimumSize: const Size(double.infinity, 54),
                  backgroundColor: colorScheme.primary,
                  foregroundColor: Colors.white,
                  shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(12),
                  ),
                ),
              ),
              const SizedBox(height: 12),
              OutlinedButton.icon(
                onPressed: _isLoading ? null : () => Navigator.pop(context),
                icon: const Icon(Icons.close),
                label: const Text("Cancel"),
                style: OutlinedButton.styleFrom(
                  minimumSize: const Size(double.infinity, 54),
                  shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(12),
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

class _FormField extends StatelessWidget {
  final TextEditingController controller;
  final IconData icon;
  final String label;
  final String hint;
  final TextInputType? keyboardType;

  const _FormField({
    required this.controller,
    required this.icon,
    required this.label,
    required this.hint,
    this.keyboardType,
  });

  @override
  Widget build(BuildContext context) {
    final isDark = Theme.of(context).brightness == Brightness.dark;

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          label,
          style: TextStyle(
            fontSize: 14,
            fontWeight: FontWeight.w600,
            color: Colors.grey[700],
          ),
        ),
        const SizedBox(height: 8),
        TextFormField(
          controller: controller,
          keyboardType: keyboardType,
          decoration: InputDecoration(
            hintText: hint,
            prefixIcon: Icon(icon),
            filled: true,
            fillColor: isDark ? const Color(0xFF1F1B18) : Colors.white,
            border: OutlineInputBorder(
              borderRadius: BorderRadius.circular(12),
              borderSide: BorderSide(color: Colors.grey[300]!),
            ),
            enabledBorder: OutlineInputBorder(
              borderRadius: BorderRadius.circular(12),
              borderSide: BorderSide(
                color:
                    isDark ? const Color(0xFF2A2420) : const Color(0xFFE8E0D5),
              ),
            ),
            focusedBorder: OutlineInputBorder(
              borderRadius: BorderRadius.circular(12),
              borderSide: BorderSide(
                  color: Theme.of(context).colorScheme.primary, width: 2),
            ),
          ),
          validator: (value) =>
              value == null || value.isEmpty ? 'This field is required' : null,
        ),
      ],
    );
  }
}

class _HealthStatusChip extends StatelessWidget {
  final String label;
  final IconData icon;
  final Color color;
  final bool isSelected;
  final VoidCallback onTap;

  const _HealthStatusChip({
    required this.label,
    required this.icon,
    required this.color,
    required this.isSelected,
    required this.onTap,
  });

  @override
  Widget build(BuildContext context) {
    return InkWell(
      onTap: onTap,
      borderRadius: BorderRadius.circular(12),
      child: Container(
        padding: const EdgeInsets.symmetric(vertical: 12),
        decoration: BoxDecoration(
          color: isSelected ? color.withOpacity(0.1) : Colors.transparent,
          border: Border.all(
            color: isSelected ? color : Colors.grey[300]!,
            width: isSelected ? 2 : 1,
          ),
          borderRadius: BorderRadius.circular(12),
        ),
        child: Column(
          children: [
            Icon(icon, size: 20, color: isSelected ? color : Colors.grey[600]),
            const SizedBox(height: 4),
            Text(
              label,
              style: TextStyle(
                fontSize: 11,
                fontWeight: isSelected ? FontWeight.w600 : FontWeight.normal,
                color: isSelected ? color : Colors.grey[600],
              ),
            ),
          ],
        ),
      ),
    );
  }
}
